<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Server</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
        <PackageReference Include="RoyalApps.RoyalTerminal.Terminal.Pty.Platform"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared\RemoteOS.Protocol\RemoteOS.Protocol.csproj" />
    </ItemGroup>

</Project>
