<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>WindowManager</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RemoteOS.Core\RemoteOS.Core.csproj" />
      <ProjectReference Include="..\RemoteOS.UI\RemoteOS.UI.csproj" />
    </ItemGroup>

</Project>
