<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>RemoteOS.UI</RootNamespace>
        <AvaloniaBuildTelemetryOptOut>true</AvaloniaBuildTelemetryOptOut>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RemoteOS.Core\RemoteOS.Core.csproj" />
    </ItemGroup>

</Project>
