<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>RemoteOS.Example.VideoPlayer</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Framework\RemoteOS.App.SDK\RemoteOS.App.SDK.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LibVLCSharp.Avalonia" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Localization\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
